# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_auto_20171129_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='noti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti', models.CharField(max_length=250)),
            ],
        ),
    ]
